applicationName: cma-app


namespace: cma-app-prod

image:
  # name: 796347764150.dkr.ecr.eu-west-2.amazonaws.com/cma-service/cma-app
  tag: "1.0"


cmaservice: cma-app-service
serviceingress:  cma-ingress-service
cma-app-baseURL : cma-app-prod.globalfrontierlink.co.uk